# Generated by Django 5.0 on 2025-11-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Yasaklı IP',
                'verbose_name_plural': "Yasaklı IP'ler",
                'ordering': ['-banned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('file_size', models.IntegerField()),
            ],
            options={
                'verbose_name': 'İşlenmiş Resim',
                'verbose_name_plural': 'İşlenmiş Resimler',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('requested_url', models.CharField(max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Şüpheli Aktivite',
                'verbose_name_plural': 'Şüpheli Aktiviteler',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rate Limit Kaydı',
                'verbose_name_plural': 'Rate Limit Kayıtları',
                'indexes': [models.Index(fields=['ip_address', 'timestamp'], name='remover_rat_ip_addr_48f84d_idx')],
            },
        ),
    ]
